### ISSUE TITLE
Can not login using Google account.

### ISSUE THREAD

**Issue by phuwanutj** [lisbono2001/Covid19-Tracker#101]
URL: https://covid-tracker-ske17.herokuapp.com/

When I try to login using my google account, I got "400: redirect_uri_mismatch" as an error message. It said that the redirect URI in 
the request does not match the ones authorized for the OAuth client.

How to reproduce:
1. Click Login with Google button below the page.

**Comment by bhatara007** [comment]
This issue fixed but we deploy to our cloud server for 1-2 days.

Thanks for your report bro!
