### ISSUE TITLE
Can't login with Github 

### ISSUE THREAD

**Issue by ttxking** [lisbono2001/Covid19-Tracker#103]
I tried to log in with Github the page is shown:

<img width="1679" alt="Screen Shot 2563-12-03 at 23 46 12" src="https://user-images.githubusercontent.com/59836666/101060470-09d7d780-35c2-11eb-8551-1eecd8899787.png">

URL: http://localhost:8000/country?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=AWTbHBJOUUHpfJYMlNjfFtyWlOKifQyK

Reproduce :
1. Invoke https://covidtracker-isp.herokuapp.com/country/ without login
2. It will redirect to https://covidtracker-isp.herokuapp.com/accounts/login/?next=/country/
3. Click login with Github

**Comment by bhatara007** [comment]
We just removed GitHub login authentication now it has some a bit problem.

Thanks for your report dude.
