### ISSUE TITLE
Continue with Github button doesn't show on homepage

### ISSUE THREAD

**Issue by ttxking** [lisbono2001/Covid19-Tracker#104]
When I try to invoke some URL, it redirects to the login page which contains Github button.
However, the homepage doesn't have the continue with GitHub button

Login page
<img width="975" alt="Screen Shot 2563-12-03 at 23 56 12" src="https://user-images.githubusercontent.com/59836666/101061491-245e8080-35c3-11eb-94f3-e3b34b2fd37d.png">

Home page
<img width="1677" alt="Screen Shot 2563-12-03 at 23 55 07" src="https://user-images.githubusercontent.com/59836666/101061387-0729b200-35c3-11eb-82e0-6b3a6a795e79.png">

URL homepage: https://covidtracker-isp.herokuapp.com/
URL of the login page: https://covidtracker-isp.herokuapp.com/accounts/login/?next=/country/

Reproduce step:
1. Just go to the homepage with URL above
2. Try to invoke something without logging in 
3. The login page will be shown
4. Compare the home page and login page

**Comment by bhatara007** [comment]
I already fixed it but waiting to deploy to our server for 1-2 days

Thanks for your report!
