### ISSUE TITLE
Functionality: Submitting empty search got Error 500

### ISSUE THREAD

**Issue by pattarinn** [lisbono2001/Covid19-Tracker#105]
If the search field is empty and the submit button is clicked many times, I got this
<img width="792" alt="Screen Shot 2563-12-04 at 21 06 13" src="https://user-images.githubusercontent.com/59819965/101173290-e7eb5d00-3674-11eb-9fb1-591ad47b6813.png">

**Comment by Noboomta** [comment]
Bye bye my server 👋
