### ISSUE TITLE
Whole server down due to error 500

### ISSUE THREAD

**Issue by pattarinn** [lisbono2001/Covid19-Tracker#106]
The consequence of issue #105, when I logged in again, I got error 500. Even I signed up for a new account I still got error 500 when I logged in. It's like if the error occurs, the whole server will be down.

**Comment by Noboomta** [comment]
Sad news, but **thanks** for your effort
we will be discuss how to fix this problems, but I _did_ repair temporarily by deploying it again. 👾😅
