### ISSUE TITLE
Heroku caching error

### ISSUE THREAD

**Issue by lisbono2001** [lisbono2001/Covid19-Tracker#108]
I thought that caching error due to caching of web browsers but the problem is from Heroku, it's caching everything to reduce loading of itself.

Problem we found:
Puvana logged-in before me 2 minutes, he tried chose and the pinned area, he found that cache fixing that pushed is not working, same errors occurred. After that I logged-in using different account but when I selected same countries that Puvana chose, all information on the page I got was as same as Puvana's.

You guys have any idea? Should we use new deployer instead?

**Comment by bhatara007** [comment]
Good idea bro, Can we try? @Noboomta @toey10112

**Comment by Noboomta** [comment]
😱👾😓

**Comment by lisbono2001** [comment]
I think that is it because we build an object outside request view function in views.py file? That's may the reason that conflict with other user data. 
If it true, we may have to slow down some part of our web-page to fix that.

**Comment by lisbono2001** [comment]
Problem solved, the error caused of comment above.
