### ISSUE TITLE
Can't use both bootstrap and my own css at the same time

### ISSUE THREAD

**Issue by lisbono2001** [lisbono2001/Covid19-Tracker#58]
I'm trying to add texts on a image in carousel slide and I want it to placed on the centre of the image so I have to use my CSS overlay Bootstrap but it came out like this.
### This is what I tried
index.html
```
{% load static %}
  <link rel="stylesheet" href="{% static 'covid_web/bootstrap/css/bootstrap.css' %}" />
{% load static %}
  <link rel="stylesheet" href="{% static 'covid_web/styles.css' %}" />
```
### this is work but I don't like to dirty the html file (style in line work too)
index.html
```
<link rel="stylesheet" href="{% static 'covid_web/bootstrap/css/bootstrap.css' %}" />
<style>
   .carousel-item.active,
   .carousel-item-next,
   .carousel-item-prev{
       display:block;
   }
</style>
```
Do you guys have any idea?

**Comment by Noboomta** [comment]
I'm not sure what you means, but hope this web can help you [https://discuss.codecademy.com/t/can-you-apply-multiple-stylesheets-to-a-single-page/369792](url)

**Comment by lisbono2001** [comment]
I tried but it's doesn't work😥.

**Comment by lisbono2001** [comment]
Never-mind, Since after I finished the index page and I didn't use extra css much so I think some <style> in <head> is OK.
