### ISSUE TITLE
Missing migrate step.

### ISSUE THREAD

**Issue by Sahadporn** [lisbono2001/Covid19-Tracker#87]
I cloned your project and tried to run it according to your instructions but I can't login or create any new account, it will cause an error 'no such table: auth_user'.
I need to run the
```
py manage.py migrate
```
first to be able to create an account.

**Comment by Noboomta** [comment]
**Thank** for your suggestion, sorry about that.

**Comment by toey10112** [comment]
I already add it.Can you try install again?
