### ISSUE TITLE
Missing to install important software in requirements.txt step

### ISSUE THREAD

**Issue by nuttapol-kor** [lisbono2001/Covid19-Tracker#90]
I think you should use requirements.txt to install all the essentials software.

**Comment by bhatara007** [comment]
Our team already have requirements.txt, Can you explain more?

**Comment by nuttapol-kor** [comment]
Oh. I mean, your team forgot to tell users to install requirements.txt in instructions.

**Comment by bhatara007** [comment]
Fixed Thank you for your report bro.

**Comment by toey10112** [comment]
I already add it. Can you try again?

**Comment by nuttapol-kor** [comment]
I did all the steps in the instructions and the web app worked fine. Nice!! 💯 💯

**Comment by toey10112** [comment]
Thank you.
